<?php
/**
 * @var RyaanAnthony_FunForms_Block_Form $this
 */
?>
<form action="<?php echo $this->getFormAction(); ?>" id="funForms" method="post">
    <div class="fieldset">
        <label for="field-subject" class="required"><?php echo $this->__('Subject') ?></label>
        <div class="input-box">
            <input name="funforms[subject]" id="field-subject" title="Subject" class="input-text required-entry" type="text" />
        </div>
        <label for="field-message" class="required"><?php echo $this->__('Message') ?></label>
        <div class="input-box">
            <textarea name="funforms[message]" id="field-message" title="Message" class="input-text required-entry" type="text" cols="5" rows="3"></textarea>
        </div>
    </div>
    <div class="buttons-set">
        <button type="submit" class="button">
            <span>
                <span><?php echo $this->__('Submit') ?></span>
            </span>
        </button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var funForms = new VarienForm('funForms', true);
    //]]>
</script>
